### PR TITLE
allow to read file that saved in other encodings then utf-8

### PR DESCRIPTION
**Pull request by bikov**
In some of our cases we use this package to store configuration and it's very annoying to save the file as utf-8 in every change

### CODE REVIEW

**Comment by jviotti** [comment]
Hey @bikov ,

Sounds great! I think Travis is failing for unrelated reasons. Let me restart and merge/release in a bit.

**Comment by jviotti** [comment]
@bikov Can you please rebase this PR? I fixed Travis in here: https://github.com/electron-userland/electron-json-storage/pull/134, but I can't rebase your PR myself :)

**Comment by bikov** [comment]
> @bikov Can you please rebase this PR? I fixed Travis in here: #134, but I can't rebase your PR myself :)

Hi. I have merged the PR but looks like `continuous-integration/appveyor/branch` isn't running at all

**Comment by jviotti** [comment]
@ckerr, @codebytere, @felixrieseberg, @jkleinsc, @lee-dohm, @malept, @MarshallOfSound, @zcbenz (sorry for the large amount of pings) Can you please make the `continuous-integration/appveyor/branch` check optional, as Appveyor won't trigger the branch job on external PRs (I don't have enough access)?

Thanks a lot! :)

**Comment by malept** [comment]
You should be able to do that yourself by limiting the branches tested by CI to master (and optionally tagged versions). Here's an example in Electron Packager:

https://github.com/electron/electron-packager/blob/dd1d9b2ee5d5980cea3c1d8424d02fb51ff78739/test/ci/appveyor.yml#L10-L12

**Comment by jviotti** [comment]
@malept Great tip. I'll try that now. Thanks a lot!

**Comment by jviotti** [comment]
@malept Hang on, wouldn't that make Appveyor not report status checks on any branch other than master? If so, that won't fix the problem, as this repository expects the branch status check to pass in order for me to be able to merge.

**Comment by malept** [comment]
I think try it first, and then if it doesn't go away, I'll look into it.

**Comment by jviotti** [comment]
@malept Check https://github.com/electron-userland/electron-json-storage/pull/135. The branch Appveyor status check is now not triggering even for me, so I can't merge my own PR either:

Screenshot 2019-08-12 at 19 26 20

**Comment by malept** [comment]
Interesting. OK, I've removed the branch check.

**Comment by jviotti** [comment]
Thanks a lot @malept!

**Comment by jviotti** [comment]
@bikov Published as v4.1.7

**Pull request merged**
